<?php
namespace App\Controller\Admin;

use Cake\Controller\Controller;
use Cake\Event\Event;

/**
 *
 */
class AppController extends Controller {

    public function beforeFilter(Event $event)
    {
        $this->Auth->deny();

        return parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    public function initialize() {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');

        $this->loadComponent('Auth');
        $this->set('current_user', $this->Auth->user());
        $this->viewBuilder()->layout('admin');
    }
}
