<?php
namespace App\Controller\Admin;

use Cake\Network\Exception\NotFoundException;
use Cake\Validation\Validator;
use Cake\Utility\Text;

class CategoriesController extends AppController {

    public function index()
    {
        parent::index(); // TODO: Change the autogenerated stub
        $this->set('title_of_layout', 'Categories');
        $this->loadModel('Categories');
        $this->paginate = [
            'limit' => 10,
            'order' => [
                'Categories.id' => 'desc'
            ]
        ];
        $categories = $this->paginate($this->Categories);
        $this->set(compact('categories'));
    }

    public function add() {
        $this->set('title_for_layout', 'Category : Add');

        $this->loadModel('Categories');
        $category = $this->Categories->newEntity($this->request->data);
        if ($this->request->is('post')) {
            //Validation
            $validator = new Validator();
            $validator
                ->requirePresence('name')
                ->notEmpty('name', 'A name is required.');
            $errors_array = $validator->errors($this->request->data);
            $error_msg = [];
            foreach($errors_array as $errors) {
                if(is_array($errors)) {
                    foreach($errors as $error) {
                        $error_msg[] = $error;
                    }
                } else {
                    $error_msg[] = $errors;
                }
            }
            if(!empty($error_msg)) {
                $this->Flash->set('Please fix the following error(s): '.implode('\n \r', $error_msg), [
                        'element' => 'error',
                        'params' => [
                            'class' => 'danger'
                        ]]
                );
                $this->redirect(['action' => 'add']);
            }

            //Save
            if ($this->Categories->save($category)) {
                $this->Flash->set('The category has been saved.', [
                        'element' => 'success',
                        'params' => [
                            'class' => 'success'
                        ]]
                );
                $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->set('Unable to add category.',
                    ['element' => 'alert-box',
                        'params' => [
                            'class' => 'danger'
                        ]]
                );
                $this->Flash->set('Unable to add category.', [
                        'element' => 'error',
                        'params' => [
                            'class' => 'danger'
                        ]]
                );
            }
        }
        $this->set(compact('category'));
    }

    public function edit($id = NULL) {

    }

    public function delete($id = NULL) {

    }
}
