<?php
/**
 * Created by PhpStorm.
 * User: xiao555
 * Date: 2017/6/26
 * Time: 下午10:46
 */

namespace App\Controller;

use Cake\Controller\Controller;
use Cake\Event\Event;

class AdminController extends AppController {

    public function beforeFilter(Event $event)
    {
        $this->Auth->deny();
        $this->viewBuilder()->layout('admin');
        return parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    public function initialize()
    {
        $pages_array = array
        (
            array(
                "Dashboard",
                "".BASE_URL."/admin",
                array('dashboard'),
                '<span class="glyphicon glyphicon-home" aria-hidden="true"></span>'
            ),
            array(
                "Posts",
                "".BASE_URL."/admin/articles",
                array('admin/articles', 'admin/articles/add', 'admin/articles/edit'),
                '<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>'
            ),
            array(
                "Categories",
                "".BASE_URL."/admin/categories",
                array('admin/categories', 'admin/categories/add', 'admin/categories/edit'),
                '<span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>'
            ),
            array(
                "Users",
                "".BASE_URL."/admin/users",
                array('admin/users', 'admin/users/add', 'admin/users/edit'),
                '<span class="glyphicon glyphicon-user" aria-hidden="true"></span>'
            )
        );

        $this->set('pages', $pages_array);
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index() {
        $this->set('title_of_layout', 'Dashboard');
    }
}