<?php
/**
 * Created by PhpStorm.
 * User: xiao555
 * Date: 2017/6/26
 * Time: 下午10:46
 */

namespace App\Controller;

use Cake\Controller\Controller;
use Cake\Event\Event;

class AdminController extends AppController {

    public function beforeFilter(Event $event)
    {
        $this->Auth->deny();
        $this->viewBuilder()->layout('admin');
        return parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    public function index() {
        $this->set('title_of_layout', 'Dashboard');

    }
}