<?php
namespace App\Controller;

use Cake\Event\Event;

class UsersController extends AppController {
    public function beforeFilter(Event $event)
    {
        $this->Auth->deny();
        return parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    public function login() {
        $this->set('title_of_layout', '登录');

        if ($this->request->is('post')) {
            $user = $this->Auth->identify();
            if ($user) {
                $this->Auth->setUser($user);
                $this->Flash->set('Logged in!', [
                        'element' => 'success',
                        'params' => [
                            'class' => 'success'
                        ]]
                );
                return $this->redirect($this->Auth->redirectUrl());
            } else {
                $this->Flash->set('Invalid username or password, try again', [
                        'element' => 'error',
                        'params' => [
                            'class' => 'danger'
                        ]]
                );
            }
        }
    }

    public function logout() {
        $this->Flash->set('Logged out!', [
                'element' => 'success',
                'params' => [
                    'class' => 'success'
                ]]
        );
        return $this->redirect($this->Auth->logout());
    }
}


