<?php
/**
 * Created by PhpStorm.
 * User: xiao555
 * Date: 2017/6/28
 * Time: 下午10:17
 */

namespace App\Model\Table;

use Cake\ORM\Table;

class ArticlesTable extends Table {
    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub

        $this->table('articles');

        $this->belongsToMany('categories', [
            'className' => 'Categories',
            'joinTable' => 'category_article'
        ]);

        $this->belongsTo('users');

    }
}